---
name: AR-Controller Actions
on: workflow_dispatch 
env:
  AWS_REGION: us-east-1
jobs:
  BUILD_AND_PUBLISH:
#    needs: Testing
    runs-on: ubuntu-latest
    steps:
      - name: code checkout
        uses: actions/checkout@v4
      - name: upload image to ECR
        uses: ar/docker-ecr-action@master
        with:
          access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          registry: ${{ secrets.REGISTRY }}
          repo: ${{ secrets.REPOSITORY }}
          region: ${{ env.AWS_REGION }}
          tags: ${{ github.run_number }}
          daemon_off: false
          dockerfile: ./Dockerfile
          context: ./
      - name: Update Image tag
        run: |
          sed -i "s|image:.*|image: ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/${{ secrets.REPOSITORY }}:${{ github.run_number }} |" ./Deployment/controller-deployment.yaml
      - name: Commit changes
        run: |
          git config --global user.name ${{ secrets.USER_NAME }}
          git config --global user.email ${{ secrets.USER_MAIL }}
          git add java.yaml
          git commit -m "Update image to ${{ github.run_number }}"
          git push
