name: Hprofile Actions
on: workflow_dispatch   # [push, workflow_dispatch]
env:
  AWS_REGION: us-east-1
jobs:      
  DEPLOY:
    # needs: BUILD_AND_PUBLISH
    runs-on: ubuntu-latest
    steps:
      - name: code checkout
        uses: actions/checkout@v4  
        with:
          access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          region: ${{ env.AWS_REGION }}
      
      - name: update kube config
        run: aws eks update-kubeconfig --region us-east-1 --name demo-cluster

      - name: Deploy to EKS cluster
        run: |

          kubectl apply -f java.yaml

