name: Hprofile Actions
#on: workflow_dispatch   # [push, workflow_dispatch]
on:
  pull_request:
    types:
      - closed # Trigger the workflow when a pull request is closed
env:
  AWS_REGION: us-east-1
jobs: 

  If_merged:
    if: github.event.pull_request.merged == true # Check if the pull request was merged
    runs-on: ubuntu-latest # Specify the runner
    steps:
    - run: |
        echo The PR was merged # Print a message if the pull request was merged

  Testing:
    needs: If_merged
    runs-on: ubuntu-latest
    steps:
    
      - name: code checkout
        uses: actions/checkout@v4

      - name: Maven test
        run: mvn test
        
      - name: Checkstyle
        run: mvn checkstyle:checkstyle

      - name: Set Java 11
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'

      - name: Setup SonarQube
        uses: warchant/setup-sonar-scanner@v7
